spring:
    jpa:
      database: POSTGRESQL
      hibernate:
          ddl-auto: none
      show-sql: true
      properties:
          hibernate.format_sql: true
    datasource:
      platform: postgres
      username: world
      password: world123
    profiles.active: ${activeProf}      





